[toolchain]
anchor_version = "0.29.0"
solana_version = "2.0.19"

[features]
seeds = false
skip-lint = false

[programs.localnet]
cream-pad = "5sqESwK18j9eH8wk58bZocg2eytvQgJvtJgBq3f1MXEs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/bilalafzal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./dep/metadata.so"